youtube = [
    "@CKGOChannelShow",
    "@3blue1brown",
    "@巫师财经",
    "@xiao_lin_shuo",
    "@MeiTouJun",
    "@TheMarketMemo",
    "@WhiteboardCrypto",
    "@entreprenuership_opportunities",
]

podcast = [
    "a16z Podcast",
    "NVIDIA Podcast",
    "Decoder with Nilay Patel",
    "Greymatter",
    "Training Data Sequoia Capital",
    "Lenny's Podcast: Product | Growth | Career",
    "Lightcone Podcast",
    "一席",
    "起朱楼宴宾客",
    "张小珺Jùn｜商业访谈录",
]

newsletter = [
    "placeholder",
]

[[website]]
channel = "远川研究所 (36氪)"
source_url = "https://36kr.com/user/5294210"

[[website]]
channel = "远川投资评论 (36氪)"
source_url = "https://36kr.com/user/5294208"

[[website]]
channel = "远川科技评论 (36氪)"
source_url = "https://36kr.com/user/5060931"

[[website]]
channel = "有数DataVision (36氪)"
source_url = "https://36kr.com/user/5294205"

[[website]]
channel = "阑夕（36氪）"
source_url = "https://36kr.com/user/1883914730"

[[bilibili]]
uid = 946974
name = "影视飓风"

[[bilibili]]
uid = 1395043421
name = "JoeCreator"

[[bilibili]]
uid = 21950148
name = "杨光_建厨师"

[[bilibili]]
uid = 407054668
name = "亿点点不一样"

[[bilibili]]
uid = 401237301
name = "赫有声"

[[bilibili]]
uid = 1195284234
name = "李白尼的猜想"

[[bilibili]]
uid = 28239752
name = "苍小天然呆bb"

[[bilibili]]
uid = 254463269
name = "毕导"

[[bilibili]]
uid = 39627524
name = "食贫道"

[[bilibili]]
uid = 261485584
name = "HOPICO"

[[bilibili]]
uid = 14583962
name = "思维实验室"

[[bilibili]]
uid = 23947287
name = "小约翰可汗"

[[bilibili]]
uid = 693450094
name = "磕书的阿冉叔"

[[bilibili]]
uid = 253553776
name = "饭统戴老板"

[[bilibili]]
uid = 49246269
name = "大象放映室"