["https://36kr.com"]
gateway_scraper = "playwright" # basic or playwright, the scraper type for the gateway
content_scraper = "playwright" # basic or playwright, the scraper type for the content
gateway_parser = "36kr"
content_parser = "36kr"