# .github/workflows/daily-processing.yml
name: Daily Content Processing

on:
  schedule:
    # Run at 6:00 PM New York time (22:00 UTC)
    - cron: '0 22 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  process-content:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install openai notion-client google-api-python-client loguru python-dotenv
          
      - name: Run retrieve job
        run: python -m jobs.retrieve
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          
      - name: Run filter job
        run: python -m jobs.filter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        
      - name: Run preprocess job
        run: python -m jobs.preprocess
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          
      - name: Run publish job
        run: python -m jobs.publish
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
